### PR TITLE
Add plane direction getting function

### PR DESCRIPTION
**Pull request by rondoor124**
Hi @pablo-mayrgundter, I fixed url change issue when the url has plane direction information.

e.g.
https://deploy-preview-546--bldrs-share.netlify.app/share/v/p/index.ifc#c:-68.42,82.2,88.33,-43.48,15.73,-4.34::p:y=-4.500826166251047
is changed to
https://deploy-preview-546--bldrs-share.netlify.app/share/v/p/index.ifc#c:-68.42,82.2,88.33,-43.48,15.73,-4.34::p:y

Please check the result and give me feedback.

### CODE REVIEW

**Comment by pablo-mayrgundter** [comment]
Just checking.. did you see the comment I left on #544 last week?  Still not seeing the new format I suggested...

image

**Comment by rondoor124** [comment]
@pablo-mayrgundter, I have fixed it preparing multi plane clipping, i'm ready to work on multi plane clipping logic after the api logic is finished.

**Comment by rondoor124** [comment]
`PTAL`

**Comment by pablo-mayrgundter** [comment]
Cool to see the multi-select working :)

I'm seeing problems with the URL format tho.  Please re-read the issue and wiki on URL structure

image

**Review by pablo-mayrgundter — APPROVED** [review]

**Pull request merged**
