### PR TITLE
Minor UI fixes: Search + Versions panel

### PR DESCRIPTION
**Pull request by OlegMoshkovich**
This PR:
- Sets the width of the search bar to match the width of other panels.
- Adds an adornment to the TextField component of the search bar to clear the input, ensuring the search string does not overlap with the clear icon.
- Sets the search TextField to multiline to accommodate long GitHub strings.
- Moves the versions panel to the same location as the nav tree panel.

# Updated
[percy](https://percy.io/8fe2b2f1/share/builds/34616270)

### CODE REVIEW

**Review by pablo-mayrgundter — CHANGES_REQUESTED** [review]
Code ok, let's see percy for UI change comparison

**Comment by pablo-mayrgundter** [comment]
I don't see any changes to search in Percy.  Shouldn't we see them in the search-100 tests?

**Comment by pablo-mayrgundter** [comment]
Oh whoops, I do see it.  But also a flake.  Can you add waits for those to deflake?

This is the intended change:
image

These are the flakes:
image

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter notes tests should not be a part of this PR. 
it should be addressed separately.

Updated percy run - PTAL

**Review by nickcastel50 — APPROVED** [review]
LGTM

**Review by OlegMoshkovich — COMMENTED** [review]
Created a ticket to deal with notes percy flakes.

**Pull request merged**
