### PR TITLE
Initial Storybook integration

### PR DESCRIPTION
**Pull request by oogali**
This PR is an initial pass at adding Storybook to the project.

It also defines stories for some existing button components.

image

### CODE REVIEW

**Review by pablo-mayrgundter — COMMENTED** [review]
Cool!

Is there any way to preview this?

**Comment by oogali** [comment]
@pablo-mayrgundter Clone locally then run `yarn storybook`.

**Review by pablo-mayrgundter — APPROVED** [review]
Works for me!

Go ahead and submit.  Please also start a section or sub-page to the Dev Guide with basics on how to use it, like the yarn command and link to the docs.

**Comment by oogali** [comment]
@pablo-mayrgundter @OlegMoshkovich https://github.com/bldrs-ai/Share/wiki/Developer-Guide#storybook

**Pull request merged**
