### PR TITLE
Update types for location

### PR DESCRIPTION
**Pull request by oo-bldrs**
PR to update the location handling functions to use the Location type.

This uses the type and shape from the history react-router package, since the native DOM type is immutable (which prevents instantiation for testing).

It's not a big deal since the input into these functions is the location object emitted from react-router.

### CODE REVIEW

**Comment by pablo-mayrgundter** [comment]
Looks good, but wanted to check what these are:

image

**Comment by oo-bldrs** [comment]
@pablo-mayrgundter I think I mixed in some TypeScript syntax in my pull request. I'll clean it up and move it out of draft status.

**Comment by pablo-mayrgundter** [comment]
ping

**Comment by OlegMoshkovich** [comment]
ping

**Pull request closed without merging**
