### PR TITLE
Allow page refresh for private models

### PR DESCRIPTION
**Pull request by oo-bldrs**
If a logged in user tries to initiate a page refresh of a private model, this will result in the user receiving a "Not Found" error because the authentication flow with Auth0 has not been completed prior to the application attempting to load the model. Specifically, GitHub returns a 404 if any client attempts to access a resource for which they have no authorization for.

This PR adds logic to block the loading of a model until after the authentication flow has been completed.

### CODE REVIEW

**Review by pablo-mayrgundter — APPROVED** [review]
Nice!!

**Comment by oogali** [comment]
Fixes #637

**Comment by pablo-mayrgundter** [comment]
Hi @oogali this was approved and still seems to work.  Please do merge!

**Comment by oo-bldrs** [comment]
It does not work. It might appear to but it is breaking unit tests.

**Comment by pablo-mayrgundter** [comment]
Ah bummer.  Flipping to draft in the meantime

**Comment by pablo-mayrgundter** [comment]
Heya, how's this looking?  Getting on towards 3 weeks

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter @oo-bldrs shall we close it - has been almost a year.

**Comment by pablo-mayrgundter** [comment]
@nickcastel50 can you review and decide how to proceed here?  It's related to your current Save work.

**Comment by nickcastel50** [comment]
> @nickcastel50 can you review and decide how to proceed here? It's related to your current Save work.

Will have a look

**Comment by pablo-mayrgundter** [comment]
Fixed by Nick's work with OPFS in #887 and #888

**Pull request closed without merging**
