### PR TITLE
Simplify style 

### PR DESCRIPTION
**Pull request by OlegMoshkovich**
This PR is meant to simplify styles to follow MUI conventions.

### CODE REVIEW

**Review by pablo-mayrgundter — CHANGES_REQUESTED** [review]
Looks great!

As discussed:
 - Add padding below dialog buttons
 - Shared corner style for Notes and other components
 
 Let me take one more look when you've done this to QA
 
Also as separate PR, let's move to mui icons

**Comment by oogali** [comment]
FYI, this is failing tests because you've changed the label for the sample IFC models.

The E2E tests are looking for `Sample Projects`, so you'll need to update the tests with the new label value.

**Comment by OlegMoshkovich** [comment]
@oogali changed the labels for sample project, but the tests are still failing.

**Review by OlegMoshkovich — COMMENTED** [review]
image

Getting a lot of errors related to loaders. 
@pablo-mayrgundter can you please take a look, when you have a chance, if it is not too distracting.

**Comment by pablo-mayrgundter** [comment]
> image
> Getting a lot of errors related to loaders. @pablo-mayrgundter can you please take a look, when you have a chance, if it is not too distracting.

Can you send more context?  I just checked out this PR and it builds and tests fine.

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter PTAL
image
Fix the end to end test error on linux, but there is another error on windows that I am not sure about.

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter PTAL - all the tests are passing and the branch is up to date.

**Comment by pablo-mayrgundter** [comment]
Only quirk is not all boxes have same corners.  In NavTree, the TreeItems are still rounded.

I personally prefer keeping the rounding on text at least.  Perhaps also on buttons.

Also would be nice to have Open tooltip line up to either cover "Search" or line up nicely

Go ahead and submit if you'd like and we can fix these up after

**Review by pablo-mayrgundter — APPROVED** [review]
See my last comment

**Pull request merged**
