### PR TITLE
add guide link to the about panel

### PR DESCRIPTION
**Pull request by OlegMoshkovich**
Add guide link to the about panel which points to the guide in the notes.

### CODE REVIEW

**Review by pablo-mayrgundter — COMMENTED** [review]
Hey, I like this idea, but can't read it myself.. too small.  I'm also noticing the other text in the about has become 0.9.. I can read it but not great.

Trying to think how to make the text in the graphic responsive.  Can you make a lookalike SVG in Figma?  We could also style it according to theme then

**Comment by OlegMoshkovich** [comment]
If you click on the graphic, it is suppose to take you to the note where all of the features are explained in more detail.

**Comment by OlegMoshkovich** [comment]
This is also a first step towards a better solution.

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter individual note sharing was broken, fixed now - which will enabling opening a guide now when the guide graphic is clicked.

**Comment by pablo-mayrgundter** [comment]
Heya, see my comment on that PR.. it fixed the individual note sharing, but then re-broke, #314

**Pull request closed without merging**
