### PR TITLE
Major refactor

### PR DESCRIPTION
**Pull request by pablo-mayrgundter**
Started as a Logo change 🤦🏻‍♂️

## Build
esbuild: refactor configs into prod/cypres/dev files; use first-class js values in defines; remove these defines from gha config

### Components
ItemProperties* -> Properties/*
LoginMenu* -> Persona/*
Logo* -> Logo/*
Nav* -> NavTree/*
{Open,Save}Model.. -> Open/*
Search* -> Search/*
delete: BranchesControl, GuideControl, ItemPanelControl
### Misc
utils/GitHub -> net/github/{Issues,Commits,...}

## Tests
- Normalize ENV vars for network services/api-handlers
- More use of narrow fixures instead of ShareMock or MockComponent
- index.jsx: enable type=module, for import.meta.url support in workers.

## Components
- All top-level buttons now ControlButtons; consistent use of url#hashTag 
- More removing custom styles everywhere in pref for Theme
- sort: useStore, useState, useHook, local var, useEffect, return <>
- pass children as `{children}` instead of e.g. `dialog={}`
- data-testid
LoginMenu: flipped day/night active

### Color
- Primary group is now 3d scene colors
- Secondary is now 2d overlay controls, panels, etc.
- index.ifc: change color to not be muted in three.js/web-ifc-three

# Style
## JSDoc
@return {ReactElement} or {React.ReactElement}

## Lint
- Import sorting
- no-magic-numbers now accepts [-10,10]

Will abandon https://github.com/bldrs-ai/Share/pull/936

### CODE REVIEW

**Comment by OlegMoshkovich** [comment]
image

**Comment by OlegMoshkovich** [comment]
image

- Menu text needs to be darker when selected.

**Comment by OlegMoshkovich** [comment]
image

- Cards don't adjust when the side drawer is resized.

**Comment by OlegMoshkovich** [comment]
image

- Need to click twice to select a card.

**Comment by OlegMoshkovich** [comment]
image

- The login menu is not positioned correctly when the side drawer is activated.

**Comment by OlegMoshkovich** [comment]
image

- The tree panel title needs to be a different color for contrast

**Comment by OlegMoshkovich** [comment]
image
- The side drawer property set panel title is underlined

**Comment by OlegMoshkovich** [comment]
image
- Cannot activate the versions panel

**Comment by OlegMoshkovich** [comment]
image
- The bot icon needs to be smaller and follow the convention of the dialog header icons

**Review by OlegMoshkovich — CHANGES_REQUESTED** [review]
Left several comments

**Review by pablo-mayrgundter — COMMENTED** [review]
- Should remove button variant
- Restore sidebar scroll position to top on drawer nav
- Remove commented code, esp for color/styles
- Check NavTree for color theme usage

**Comment by pablo-mayrgundter** [comment]
PTAL

- Menu item selected more legible.
- Cards adjust when side drawer resized.
- Panel title color contrast.
- Versions panel can be activated.
- Imagine follows dialog header convention.
- Make NavTree and Versions mutex.
- Restore version active color.
- Remove comments.

**Comment by OlegMoshkovich** [comment]
https://docs.google.com/presentation/d/1udTXNEaSthtaQ3tibQDCPM9aftBOpkVl8_92cORB4cs/edit

At the moment selected state for the button is not visible.

**Comment by OlegMoshkovich** [comment]
image

A pull box is visible on the drawer

**Comment by OlegMoshkovich** [comment]
image

Imagine buttons are hidden

**Comment by OlegMoshkovich** [comment]
image

Schneestock model gets stuck when loading :/

**Comment by OlegMoshkovich** [comment]
image

Something is happening with the camera at the moment.

When I move a camera to another position and then select an element the camera moves back to the original position.
I suspect it is because the original camera coordinates are still in the url when the selected element hash gets appended to the url.

**Comment by OlegMoshkovich** [comment]
image

Sometimes the app gets stuck - in this instance it is a bldrs plaza. A cancel option on the snack bar would be useful to get out such state.

**Comment by OlegMoshkovich** [comment]
image

Drawer on mobile is positioned behind the element group.

**Comment by OlegMoshkovich** [comment]
image

Increase the distance between the comment icon and the number of comments chip

**Comment by OlegMoshkovich** [comment]
image

Decrease the height of the imagine screenshot area and space the bottom controls.

**Comment by pablo-mayrgundter** [comment]
I fixed the Z ordering and the navtree not showing up.  for the smaller spacing/style fixes I suggest we skip for now.

**Comment by OlegMoshkovich** [comment]
Can you comment or thumb up the comments?

**Comment by OlegMoshkovich** [comment]
image

pressing back to the note list button closes the side drawer

**Comment by OlegMoshkovich** [comment]
image

in the light mode links are not visible due to the light grey color

**Comment by OlegMoshkovich** [comment]
image


this is nice!

**Comment by OlegMoshkovich** [comment]
image


since you put the search box in the middle, maybe it makes sense to finally get the controls button to align vertically?

**Comment by OlegMoshkovich** [comment]
image

Element group is misaligned on mobile

**Comment by OlegMoshkovich** [comment]
image

Tooltips should be turned off on mobile

**Comment by OlegMoshkovich** [comment]
image


logo is misaligned - maybe make it bigger to center it

**Comment by OlegMoshkovich** [comment]
image


Panels do not have a sticky header. no big deal obviously just bring it up.

**Comment by OlegMoshkovich** [comment]
image

When a path to github model isa  long strings, the search box should expand into multiple lines.

**Comment by OlegMoshkovich** [comment]
image

notes are not reachable.

**Comment by OlegMoshkovich** [comment]
image


Opening a shared link triggers the share dialog to appear.

**Comment by OlegMoshkovich** [comment]
image

The versions panel is hidden under the elements tree, before it was a toggle.

**Review by OlegMoshkovich — APPROVED** [review]

**Pull request merged**
