### PR TITLE
Introduce a user menu which includes the option to log in and the theme control

### PR DESCRIPTION
**Pull request by OlegMoshkovich**

### CODE REVIEW

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter PTAL

**Review by pablo-mayrgundter — CHANGES_REQUESTED** [review]
Lighthouse is reporting some errors.. and when I dig in I see them as well in console:

image
image
image

**Comment by pablo-mayrgundter** [comment]
Hmm, same react warning as bot link PR..

Hopefully that's a clue!  Anything that's in both but not yet in prod?

**Review by pablo-mayrgundter — APPROVED** [review]
As in 866, the react warning not related to this PR.  LGTM

**Pull request merged**
