### PR TITLE
Specify type assertion for JSON import

### PR DESCRIPTION
**Pull request by oogali**

### CODE REVIEW

**Comment by oogali** [comment]
I think it makes sense to keep this separate -- we can get this fix in without requiring us to take an immediate position on Gitpod yet.

**Comment by oogali** [comment]
@shafy In my branch, I did not add that module so I'm curious why I don't receive any errors regarding `assert`...

image

**Comment by oogali** [comment]
@shafy Never mind, I see that it's not being tested... I'll add it to the lint inputs and incorporate your module changes too.

**Comment by shafy** [comment]
Looks great to me!

**Pull request merged**
