### PR TITLE
Sidebar dragging for both Desktop and Mobile

### PR DESCRIPTION
**Pull request by ronplaymeta**
Hi @pablo-mayrgundter, I finished implementing the following features in this PR since they are related closely each other.

> Sidebar dragging for mobile
> Update dragging logic on `SideDrawer` (double-click)
> Change mobile drawer to act like desktop drawer (v -> ..., draggable, dbl-click)

Please check the result and give me feedback.
Thank you.

### CODE REVIEW

**Comment by OlegMoshkovich** [comment]
image
 HI Ron, 
I see the drag handle at the top but the dragging does not work for me yet.

**Comment by rondoor124** [comment]
https://user-images.githubusercontent.com/92342281/215495845-b1309b57-b011-41b4-9963-581bbc13b805.mp4

Hi @pablo-mayrgundter, it's working on my side, please check again.

**Comment by ronplaymeta** [comment]
`PTAL`

**Comment by pablo-mayrgundter** [comment]
please enable dblclick for desktop drag button

mobile bug:
- open notes
- dblclick drag button
- notes panel disappears, but notes button shows it's still active (bug)
- clicking notes button repeatedly doesn't open notes (bug)
- same with properties (bug)

**Comment by ronplaymeta** [comment]
PTAL

**Comment by OlegMoshkovich** [comment]
If only property panel is on the sidebar can be dragged down, not up.

**Comment by pablo-mayrgundter** [comment]
Desktop bugs
1) SideDrawer should should always take full vertical height of window (height: 100%)
image
2) dblclick button doesn't work
3) when Notes & Properties open, only Notes is visible (should be split 50/50)

Mobile bugs
1) dblclick button doesn't work at first.. open props, dblclick, nothing.  Does start to work after changing size, but can't drab above initial position.  Should be able to drag to 100% height.
2) Properties also starts at minimal size here.  Should start at same default as Notes.
image

**Comment by ronplaymeta** [comment]
PTAL

**Comment by pablo-mayrgundter** [comment]
Getting close!  per discussion, when sidedrawer is first opened, dblclick on resize button should go from default position to fullscreen.  After, if user resizes it at any point, dblclick should go between that position and default position.

**Comment by ronplaymeta** [comment]
ptal

**Pull request merged**
