### PR TITLE
Add Level Names

### PR DESCRIPTION
**Pull request by mkeshavarzi**
Addressing feature request #482 by @MarkusSteinbrecher.

### CODE REVIEW

**Review by pablo-mayrgundter — CHANGES_REQUESTED** [review]
Heya, looks like you may have a bad merge here.. there's a bunch of unrelated changes, and some files deleted that shouldn't be.. e.g. BranchesControl.jsx and its test

**Comment by MarkusSteinbrecher** [comment]
does this still need my review? It looks fine for me. I guess there where some issues with the merge?

**Comment by pablo-mayrgundter** [comment]
@mkeshavarzi could you get the merge cleaned up and let's review?

**Comment by mkeshavarzi** [comment]
@pablo-mayrgundter @MarkusSteinbrecher Will do!

**Pull request closed without merging**
