### PR TITLE
Theme work

### PR DESCRIPTION
**Pull request by pablo-mayrgundter**
Hey Oleg,

Branched from my work yesterday.  This is just focusing on theme usage and colors.  The colors are changed up a lot for testing right now.. we can get them back towards prod.  I'm basically hunting for anywhere where we're not using theme colors and using the theme color ref.  There's more to do in this direction, e.g. with fonts, padding, etc., but want to get it ready for Ron too.

### CODE REVIEW

**Review by OlegMoshkovich — CHANGES_REQUESTED** [review]
It is great to unify everything.

image

image

image


image

Would be great to have the uniform padding.

**Review by OlegMoshkovich — CHANGES_REQUESTED** [review]
Several more comments.

image

image


For marking up the views I am using these slides:
https://docs.google.com/presentation/d/1l8ykr9xG86AL1RsE8GCnH9ErzUPf8pMzhDT4Db0wM8o/edit?usp=sharing

**Comment by pablo-mayrgundter** [comment]
> It is great to unify everything.
> 
> image
> 
> image
> 
> image
> 
> image

Yeah, there's a MuiCard that I'm thinking to use for Dialogs and Notes

https://mui.com/material-ui/react-card/

**Comment by OlegMoshkovich** [comment]
The problem with mui dialogs and cards is that it has too many style constraints.

**Comment by OlegMoshkovich** [comment]
A lot of the design sketches are here 

https://www.figma.com/file/DqKVaQEukf8vVHnlwiRGhv/Screens-MVP?fuid=1142156788092030514

image


We went away from it jointly in June.

Feels like you are redesigning the whole app.

**Comment by OlegMoshkovich** [comment]
image

**Comment by OlegMoshkovich** [comment]
Overall it does feel unified.

**Pull request closed without merging**
