### PR TITLE
Viewer: Change selected and preselected colors

### PR DESCRIPTION
**Pull request by OlegMoshkovich**
This PR addresses #334.
It defines custom colors for viewer select and preselect interaction, using theme custom palette colors.

### CODE REVIEW

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter PTAL. 
this is straight forward addition and carries a lot of value.
let merge soon!

**Comment by pablo-mayrgundter** [comment]
Code looks good but I can barely see the active selection anymore.  Can you increase contrast?  I wonder too maybe it's because I'm a little color-blind so color choice might matter.  Would be nice to have it easily visible with low screen brightness too; currently not visible if I go to half brightness on my monitor.

**Comment by OlegMoshkovich** [comment]
Yes sure. there is opacity on the color at the moment - will remove.

**Comment by OlegMoshkovich** [comment]
image

@pablo-mayrgundter how about this?

**Comment by OlegMoshkovich** [comment]
@pablo-mayrgundter PTAL

**Review by pablo-mayrgundter — APPROVED** [review]

**Pull request merged**
