### PR TITLE
Add GitHub Signup and Wiki Info to Login Menu

### PR DESCRIPTION
**Pull request by OlegMoshkovich**
This PR adds a "Join GitHub" option for easy signup and an "Info" option linking to our wiki in the login menu.

### CODE REVIEW

**Review by pablo-mayrgundter — CHANGES_REQUESTED** [review]
Lg, but one rendering issue.. I think custom styles in LoginMenu should be removed.  I did that in refactor PR and it works well.  Compare below...

image

image

default styles:
image

image

**Comment by OlegMoshkovich** [comment]
Ok cool 
image

Ask working well for me.
Where did you see the overflow?

**Comment by OlegMoshkovich** [comment]
image

**Comment by OlegMoshkovich** [comment]
closing the PR because it was created before refactor.

**Pull request closed without merging**
