### PR TITLE
Apply adjustable size to the sidebar

### PR DESCRIPTION
**Pull request by rondoor124**
Hi @pablo-mayrgundter.
I made adjustable size feature to the sidebar, and it required many update of the code.
Please check the issue https://github.com/bldrs-ai/Share/issues/148 and give me feedback.
Thank you.

### CODE REVIEW

**Comment by pablo-mayrgundter** [comment]
w00t!  Super cool :)

Per discussion, please remove the new borders and revert the background color changes, and see if you can find a button for the vertical separator to help the user discover the draggable behavior.

image

**Comment by pablo-mayrgundter** [comment]
Also I think the margin for the buttons got shrunk:

image

here's the correct margin from production:

image

**Comment by rondoor124** [comment]
`PTAL`

**Comment by rondoor124** [comment]
`PTAL`

**Comment by OlegMoshkovich** [comment]
super cool!!

**Comment by pablo-mayrgundter** [comment]
Looking good!

Please use the theme for background color on the 3 dots.. it's currently white, which is fine, but might as well use the theme :)

For testing, I think there's 1 new behavior here, which is that close and open of the panel keeps the resize width.  See if you can add an expect unit test for that.

**Comment by rondoor124** [comment]
When closing the panel, the system hide only the sidebar panel, not removing, and keep the sidebar width using state, so i think it's no useful to check the panel width when toggling. :)

**Comment by rondoor124** [comment]
@OlegMoshkovich, thank you for your kind feedback. :)
yep, i think it'd be better to use the carrot to collapse and expand the below items fully instead of reducing the height to half, would like to know your suggestion. :)

**Comment by OlegMoshkovich** [comment]
The point of the collapsed half drawer is to enable the user to access notes and the viewport simultaneously - it is useful to have both as long as the user is able to scroll the notes while in the drawer is in the collapsed state.

**Comment by OlegMoshkovich** [comment]
Would be nice if you can figure out how to reduce the space at the top of the drawer.
image

This is the example sketch of the collapsed drawer.
![Uploading 215061494...]

**Comment by pablo-mayrgundter** [comment]
Guys, let's keep this focused on the side drag.  I'm going to merge

**Pull request merged**
